kind: PersistentVolume
apiVersion: v1
metadata:
  name: hostpathpradeep
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/devopsschool"

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvchostpathpradeep
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
