apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: pvchostpathamruta

spec:

  storageClassName: manual

  accessModes:

    - ReadWriteOnce

  resources:

    requests:

      storage: 1Gi
