kind: PersistentVolume
apiVersion: v1
metadata:
  name: mayank-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWrite
  hostPath:
    path: "/tmp/mike/pvData"
