apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayank-pvc
  namespace: mayank
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

