
kind: Pod
apiVersion: v1
metadata:
  name: mayank-task-pv-pod
  namespace: mayank
spec:
  containers:
    - name: mayank-task-pv-container
      image: scmgalaxy/nginx-devopsschoolv1
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mayank-task-pv-storage
  volumes:
    - name: mayank-task-pv-storage
      persistentVolumeClaim:
        claimName: mayank-pvc-1
