apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayank-pvc-1
  namespace: mayank
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi



