apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc-aj
spec:
  replicas: 5   
  template:
    metadata:
      labels:
        app: hello-world-aj
    spec:
      containers:
      - name: hello-ctr-aj
        image: scmgalaxy/nginx-devopsschoolv1
        ports:
        - containerPort: 80
