apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-ajay
  labels: 
    app1: ajaynodeport
spec:
  containers:
  - name: hello-ctr-ajay
    image: scmgalaxy/nginx-devopsschoolv1 
    ports:
    - containerPort: 80
