apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc-guna
spec:
  replicas: 4   
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-ctr-guna
        image: scmgalaxy/nginx-devopsschoolv1
        ports:
        - containerPort: 80
